name: bartts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - numba
  - arviz
  - pydantic
  - tqdm
  - matplotlib
  - python-graphviz
  - pip:
      - ray[default]
